### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by bvssvni** [tomaka/cpal#15]
Are there plans for OSX support?

**Comment by tomaka** [comment]
Just like glutin, that would be great but I can't do it myself since I don't have any mac :-/

**Comment by bvssvni** [comment]
I would like to help, but I'm clueless about where to start. Will post resources here if I come across something.

Perhaps a post in r/rust_gamedev could bring attention from somebody who knows how to do it?

**Comment by tomaka** [comment]
For those that may be coming here from reddit.

To write an implementation, just copy-paste `null/mod.rs` to `<name_of_the_api>/mod.rs`, and adjust the header in `lib.rs`.

The `Buffer` struct is how data is being submitted to the backend. If the underlying API gives you a pointer to a buffer, make `Buffer::get_buffer` return it. If however the API has a function to add data (like ALSA), make `Buffer::get_buffer` return a `Vec` and call the function in `Buffer::finish`.

**Comment by mitchmindtree** [comment]
I'm currently having a go at getting this working! I seem to have successfully compiled some generated bindings for Apple's Core Audio API and I'm about to get to work on the `core_audio/mod.rs`.

One thing I've noticed is that #[cfg(unix)] seems to trigger os x as well - by default when doing a `cargo build` on my mac it will try to find the `mod cpal_impl` in the `alsa/mod.rs` - is that expected behaviour? What `cfg` do I write to help the compiler distinguish between building on mac and on linux (I've not yet had any experience writing platform specific stuff)?

**Comment by mitchmindtree** [comment]
Hmm it seems to work if I change `#[cfg(unix)]` to `#[cfg(target_os = "linux")]` and use the following for the os x support:
```Rust
#[cfg(target_os = "macos")]
#[path="core_audio/mod.rs"]
mod cpal_impl;
```

**Comment by tomaka** [comment]
> I'm currently having a go at getting this working!

Wow, thanks! \o/
