### ISSUE TITLE
Panic when calling len() on OutputBuffer

### ISSUE THREAD

**Issue by casey** [tomaka/cpal#228]
It looks like `len` triggers the deref implementation, which panics for an `OutputBuffer`.

The error was hard to figure out, since it said "It is forbidden to read from the audio buffer", but I didn't think that I was reading it by calling `len()`. Could this be allowed or caught at compile time?

**Comment by mitchmindtree** [comment]
Thanks for the issue @casey! This definitely shouldn't happen. Which operating system are you currently using? Could you please share the entire output of the `panic!` output? If you could also use `RUST_BACKTRACE=1` so that we can see the full stack trace that would be much appreciated.

**Comment by casey** [comment]
Hey there :)

I'm using macOS 10.13.4.

Here's a repo containing a minimal example, you can trigger it by cloning it and doing cargo run. A full stack trace (which looks like it contains a rust stack trace as well as a native stack trace) is [here](https://gist.github.com/3e02d0ea497be7e1ce4e7dbcd85aff2f).

**Comment by mvdnes** [comment]
I had the same issue today. This is caused by the [Deref impl] on the OutputBuffer combined with the len implementation on the [UnknownTypeOutputBuffer]. If you call `len` on the OutputBuffer directly, it should work.

[Deref impl]: https://github.com/tomaka/cpal/blob/20fffb26fb9150ed8e1a19d3eafbf608dffa3480/src/lib.rs#L596-L605
[UnknownTypeOutputBuffer]: https://github.com/tomaka/cpal/blob/20fffb26fb9150ed8e1a19d3eafbf608dffa3480/src/lib.rs#L637-L647
