### ISSUE TITLE
A new release any time soon?

### ISSUE THREAD

**Issue by AustinJ235** [tomaka/cpal#274]
The windows destroy stream bug is a pretty major one for applications that create new streams on a regular basis. Think we could push a new version? It has been over a year after all.

**Comment by mitchmindtree** [comment]
Yes, agreed it's time for a new release! CPAL will publish a new version to crates.io automatically when a PR that updates the version in the cargo.toml is merged. Would you mind submitting a PR to update the version to 0.8.3? From a quick glance over the commits since the last version I don't think there have been any breaking changes that would require bumping to 0.9 just yet.

It probably also makes sense to do one more release before @ishitatsuyuki and I attempt to address #204 and #268 which may result in some more significant breaking changes (but hopefully nothing *too* tricky to update to).
